class CollectedDataType:
    STACK_TRACE = "STACK_TRACE"
    TRAINING_LOG = "TRAINING_LOG"
    TRAINING_METRIC = "TRAINING_METRIC"
    RESOURCE_METRIC = "RESOURCE_METRIC"
    GENERIC = "GENERIC"

class CollectedNodeType:
    TRAIN_NODE = "TRAIN_NODE"
    INFER_NODE = "INFER_NODE"
    COLOC_NODE = "COLOC_NODE"